### ISSUE TITLE
Just some issue

### ISSUE THREAD

**Issue by iMansoorAliKhan** [iMansoorAliKhan/login#1]
hey there is some issue

**Comment by deepakmaurya** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**Worker have applied to start work.**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.gitworkdone.com/profile/Prem456'>Prem456</a> has applied to start work. (Funders only: <a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works?action=approve&worker=Prem456'>approve worker</a> | <a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works?action=reject&worker=Prem456'>reject worker</a>)**
                
**Message:** Testing for contributor




<a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.gitworkdone.com/profile/Prem456'>Prem456</a> has been approved to start work.**

<hr />

**Message:** BlBlBl


<a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
**<a href='https://sandbox.gitworkdone.com/profile/iMansoorAliKhan'>iMansoorAliKhan</a> asked <a href='https://sandbox.gitworkdone.com/profile/Prem456'>Prem456</a> to stop the work on bounty <a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works'>Just trying to see how it works</a>.**
<hr />
 
**Message:** Stop working, I dont like it.


<a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
**<a href='https://sandbox.gitworkdone.com/profile/Prem456'>Prem456</a>, You have been requested to restart the work.**
<hr/>
 
**Funder Message:** Okay lets start working on it


<a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
**Work has been submitted by <a href='https://sandbox.gitworkdone.com/profile/Prem456'>Prem456</a>.**
<hr />

**Message:** submiting work


<a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
**<a href='https://sandbox.gitworkdone.com/profile/iMansoorAliKhan'>https://sandbox.gitworkdone.com/profile/Prem456</a> Work has been approved by <a href='Prem456'>iMansoorAliKhan</a>.**
<hr />

**Message:** cool Thanks


<a href='https://sandbox.gitworkdone.com/issue/just-trying-to-see-how-it-works'>Click Here to view more</a> on GitWorkDone Bounty detail page.
