### ISSUE TITLE
this issue

### ISSUE THREAD

**Issue by iMansoorAliKhan** [iMansoorAliKhan/login#2]

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**

<hr>

**Worker have applied to start work.**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.gitcommits.com/profile/aeseller'>aeseller</a> has been approved to work.**
                
**Message:** Just letting you know that I can start wrking on this real quick




<a href='https://sandbox.gitcommits.com/issue/i-need-this-issue-to-be-done-asap'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.gitcommits.com/profile/aeseller'>aeseller</a> has been approved to start work.**

<hr />

**Message:** Okay lets start


<a href='https://sandbox.gitcommits.com/issue/i-need-this-issue-to-be-done-asap'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**Work has been submitted by <a href='https://sandbox.gitcommits.com/profile/aeseller'>aeseller</a>.**
<hr />

**Message:** done


<a href='https://sandbox.gitcommits.com/issue/i-need-this-issue-to-be-done-asap'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.gitcommits.com/profile/aeseller'>aeseller</a>, Your submission has been rejected by <a href='https://sandbox.gitcommits.com/profile/olivergreen'>olivergreen</a>.**
<hr />

**Message:** need to get this done in a different way


<a href='https://sandbox.gitcommits.com/issue/i-need-this-issue-to-be-done-asap'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**Work has been submitted by <a href='https://sandbox.gitcommits.com/profile/aeseller'>aeseller</a>.**
<hr />

**Message:** Okay done it the otherway


<a href='https://sandbox.gitcommits.com/issue/i-need-this-issue-to-be-done-asap'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.gitcommits.com/profile/aeseller'>aeseller</a> Work has been approved by <a href='olivergreen'>https://sandbox.gitcommits.com/profile/olivergreen</a>.**
<hr />

**Message:** Thanks/

This is eactly what I was looking for.

Thanks
Kudos!!!!!!


<a href='https://sandbox.gitcommits.com/issue/i-need-this-issue-to-be-done-asap'>Click Here to view more</a> on GitCommits Bounty detail page.
